
modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="themadcrafter"
version="2.0.1"
displayName="TheMadCrafters Revival"
displayURL="https://www.facebook.com/groups/715208985761566"
logoFile="themadcrafter.png"
credits="eclipse and forge"
authors="Smokedogg aka TheMadCrafter"

description='''
'''

[[dependencies.themadcrafter]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.themadcrafter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
